package Proyecto_2_Codigo;

public enum TipoProducto {
	
	LLANTAS,BUJIAS,BUJES,MULETAS,BOMBAS_DE_GASOLINA,DIRECCION,BOCINAS_DE_MOTO,FRENOS_AUTOMOVILES,MOTORES,TIMONES,BOMBILLAS_DE_AUMOTOMOVILES,PRODUCTOVARIOS

}
